---
apiVersion: v1
kind: Deployment
metadata:
  name: ping-pong-deployment
  namespace: ping-pong
  labels:
    app: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
      - name: ping-pong-pod
        image: docker.io/dograjatin/ping-pong:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: ping-pong-service
  namespace: ping-pong
spec:
  type: ClusterIP
  selector:
    app: ping-pong
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080


